### ISSUE TITLE
Doesn't work with MCP v2.0

### ISSUE THREAD

**Issue by cgarling** [takashiishida/arxiv-latex-mcp#30]
With MCP package v2.0 trying to run arxiv-latex-mcp results in error

> Traceback (most recent call last):
  File "/Users/cgarling/.local/share/uv/tools/arxiv-latex-mcp/bin/arxiv-latex-mcp", line 4, in <module>
    from arxiv_latex_mcp.__main__ import main
  File "/Users/cgarling/.local/share/uv/tools/arxiv-latex-mcp/lib/python3.10/site-packages/arxiv_latex_mcp/__main__.py", line 3, in <module>
    from arxiv_latex_mcp.server import main as async_main
  File "/Users/cgarling/.local/share/uv/tools/arxiv-latex-mcp/lib/python3.10/site-packages/arxiv_latex_mcp/server.py", line 36, in <module>
    @server.set_logging_level()
AttributeError: 'Server' object has no attribute 'set_logging_level'

Recommend either updating package to be compatible with MCP v2.0 or restricting the supported versions of MCP to <2.0.
